"""empty message

Revision ID: 14472e61d677
Revises: 0d36dbdcba18
Create Date: 2022-01-03 13:47:10.960764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14472e61d677'
down_revision = '0d36dbdcba18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'author_pk',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'author_pk',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
