"""added iban column

Revision ID: a8671a0f5792
Revises: 
Create Date: 2022-01-03 11:44:59.806319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8671a0f5792'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('iban', sa.String(length=22), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'iban')
    # ### end Alembic commands ###
